#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='get_skill_data.py',
        target=ctx.path_to(ctx, 'OUT_DATA', 'data.csv'),
        name='get_skill_data'
    )
