#! pythongit st


def build(ctx):

        # Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='reg_tree.py',
            deps= ctx.path_to(ctx, 'OUT_DATA', 'data.csv')
            ,
            target=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'basic.pickle'),
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'cognitive.pickle'),
		ctx.path_to(ctx, 'OUT_ANALYSIS', 'non_cognitive.pickle'),
		 ctx.path_to(ctx, 'OUT_ANALYSIS', 'both.pickle'),
		 ctx.path_to(ctx, 'OUT_ANALYSIS', 'Occupational_results.pickle'),
		ctx.path_to(ctx, 'OUT_ANALYSIS', 'decision_tree.dot')
            ]
        )


